### ISSUE TITLE
默认props属性需要排列在前面才能生效

### ISSUE THREAD

**Issue by censujiang** [uni-helper/vite-plugin-uni-platform-modifier#2]
### 描述问题

默认props属性需要排列在前面才能生效，比如说你有一个属性is-link，你必须要在组件内将这个is-link排列在前面才能使这个全局默认值生效

### 复现

在一个组件内这么写：
```
:is-link="true" :is-link.h5="false"
```

观察发现可以生效，但是如果说这个:is-link="true"被放到后面就不能生效，在小程序平台直接显示false

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 34.60 GB / 63.95 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (117.0.2045.36)
    Internet Explorer: 11.0.19041.3636
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
试试 v0.0.2

**Comment by censujiang** [comment]
感谢您
